version: '3.1'
services:
  web:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./enterprise-17.0:/mnt/enterprise
      - ./dev-sandbox:/mnt/dev
    command: --addons-path=/mnt/enterprise,/mnt/dev -d odoo-dz-dev -u dz_manager

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-db-data:
