version: '3.1'
services:
  web:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./enterprise-17.0:/mnt/enterprise
      # - /path/to/addons2:/mnt/extra-addons2
    #command: --addons-path=/mnt/extra-addons1,/mnt/extra-addons2
    command: --addons-path=/mnt/enterprise

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-db-data:
